feat: ompi images for use with slurm (#156)
* Subject: Add OpenMPI to CPU images on slurm-images branch (#142)

These mods are essentially the same as those in the PR for branch
feature/cpu-mpi, which originally targeted master, but this mod
targets the slurm-images branch.  This mod also used the newer
Makefile, which resolves several conflicts that existed with the
original feature/cpu-mpi branch.  Each of the changes are described
below using the log from the original commits.

commit 3d5285dac32315497d841de346669867e5b95652
Author: Chris Rickett <cdrickett@gmail.com>
Date:   Mon Mar 21 11:18:20 2022 -0400

    Subject: Modify ENV settings for USE_MPI

    Description:

    This modifies how the LD_LIBRARY_PATH and PATH env vars are set so
    that they should not include the UCX/OMPI paths unless USE_MPI=1
    was
    specified.  Note that the OMPI_ALLOW* vars exist in the final
    container no matter what, however, they do not have a set value
    unless
    USE_MPI=1 was specified.

commit 4b3a7571d29e12af8f21cc3e4ceba088a9e5ee95
Author: Chris Rickett <cdrickett@gmail.com>
Date:   Fri Mar 18 09:12:09 2022 -0400

    Subject: Fix Horovod MPI args

    Description:

    Fix the ARGs used for configuring Horovod to either use MPI or
    GLOO.

commit fb8d050c2d811093b8c970cc432634117f497afc
Author: Chris Rickett <cdrickett@gmail.com>
Date:   Mon Mar 14 14:09:27 2022 -0400

    Subject: Add OpenmMPI to base CPU image

    Description:

    Dockerfile-base-cpu:

    Modified the version of g++ to get beyond a docker build failure.
    Also added in packages for including Slurm PMI/PMI2 support to
    enable
    the OpenMPI (OMPI) based Singularity containers to be launched
    from
    srun directly. Modified to use new arguments to enable building
    MPI
    support into the image. Set some env variables for installing the
    necessary components (UCX and OMPI).

    Dockerfile-default-cpu:

    Modified to use new build arguments to determine if Horovod builds
    MPI
    support or not.

    Makefile:

    Added new variables for allowing users to specify if MPI support
    should be added or not (USE_MPI).  If this is set then the
    Makefile
    passes other build args to the CPU Dockerfiles to enable Horovod
    to
    use MPI.  Also updated the base image for the CPU targets from
    Ubuntu
    18.04 to 20.04 to address issues with getting PMI/PMPI2 packages
    installed so that the OMPI based containers could be launched
    directly
    from srun rather than mpirun.

    ompi.sh:

    New file added that builds/installs the following components:

      - Mellanox OFED 5.5-1.0.3.2
      - UCX 1.10.1
      - OpenMPI 4.1

    Together these components allow the MPI inside the container to be
    used to get performant execution across nodes.

    Tested both the TF1 and TF2 build targets by doing the following:

    $> make USE_MPI="1" build-tf1-cpu >& tf1-cpu-mpi-build.txt
    $> make USE_MPI="1" build-tf2-cpu >& tf2-cpu-mpi-build.txt

    After tagging and pushing to an internal registry, I converted the
    docker images to Singularity ones with a command similar to:

    $> sudo SINGULARITY_NOHTTPS=true SINGULARITY_DISABLE_CACHE=True
    REGISTRY="my-registry:5000" NAMESPACE="" singularity -vvv build
    detAI-torch-1.9-tf-2.4-cpu-mpi.sif
    docker://my-registry:5000/determinedai/e\
nvironments:py-3.8-pytorch-1.9-lightning-1.5-tf-2.4-cpu-mpi-0.17.10

    I copied the Singularity images to an IB cluster and tested a
    couple
    different ways.  First, I tested each using the OSU MPI benchmarks
    to
    make sure I was getting the expected performance.  For example:

    [username@my-cluster detAI]$ singularity shell --bind /lus
    /lus/scratch/username/detAI/detAI-torch-1.9-tf-2.4-cpu-mpi.sif
    Singularity> pwd
    /lus/scratch/username/detAI/osu-micro-benchmarks-5.6.2
    Singularity> ./configure CC=`which mpicc` CXX=`which mpicxx`
    Singularity> make
    Singularity> exit
    exit
    [username@my-cluster detAI]$
    [username@my-cluster detAI]$ srun --mpi=pmi2 -n 2
    --ntasks-per-node=1
    singularity exec --bind /lus
    /lus/scratch/username/detAI/detAI-torch-1.9-tf-2.4-cpu-mpi.sif
    ./osu-micro-benchmarks-5.6.2/mpi/one-sided/osu_get_bw
    1                       2.30
    2                       5.22
    4                      10.42
    8                      20.67
    16                     41.49
    32                     82.13
    64                    163.81
    128                   312.84
    256                   597.39
    512                  1160.31
    1024                 2086.73
    2048                 3640.88
    4096                 5878.72
    8192                 7274.17
    16384                8869.16
    32768               10723.33
    65536               12522.77
    131072              13153.47
    262144              13502.70
    524288              13584.33
    1048576             13742.79
    2097152             13544.06
    4194304             13658.77

    This matches the expected BW performance.  I also repeated the
    same
    steps for the TF1 image and got similar results.

    I then tested a TF1 and TF2 version of the MNIST program to verify
    that Horovod init correctly sees the MPI world.  I modified the
    test
    program so that it prints the horovod rank and world size
    information
    after hvd.init().  For example, the following TF2 test was
    executed:

    [username@my-cluster detAI]$ srun --mpi=pmi2 -n 8
    --ntasks-per-node=4
    singularity exec --bind /lus
    /lus/scratch/username/detAI/detAI-torch-1.9-tf-2.4-cpu-mpi.sif
    python
    /lus/scratch/username/detAI/mnist/tensorflow2_mnist.py >& logs.txt

    Inside the logs.txt I see the following output, which verifies the
    hvd.init() correctly initialized using MPI:

    hvd.local_rank(): 1, hvd.rank(): 1, hvd.size(): 8
    hvd.local_rank(): 3, hvd.rank(): 3, hvd.size(): 8
    hvd.local_rank(): 0, hvd.rank(): 0, hvd.size(): 8
    hvd.local_rank(): 1, hvd.rank(): 5, hvd.size(): 8
    hvd.local_rank(): 0, hvd.rank(): 4, hvd.size(): 8
    hvd.local_rank(): 2, hvd.rank(): 6, hvd.size(): 8
    hvd.local_rank(): 3, hvd.rank(): 7, hvd.size(): 8
    hvd.local_rank(): 2, hvd.rank(): 2, hvd.size(): 8
    2022-03-14 10:28:29.703637: I
    tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA
    devices, tf_xla_enable_xla_devices not set
    <...snip...>

    I repeated the same steps using a TF1 version of the test and the
    TF1
    image and it also reported the correct rank/world size
    information.

Note: the image name above still refers to the older TF2 target.  This
is now updated with the recent Makefile so the build-tf2-cpu tag is:

determinedai/environments:py-3.8-pytorch-1.10-lightning-1.5-tf-2.8-cpu-mpi-0.17.12

The newer docker image was converted to Singularity in the same manner
as above and the same OSU and MNIST tests worked as expected.

* Subject: Add OpenMPI support to NVIDIA GPU targets (#144)

Description:

    This mod adds OpenMPI support to the targets for NVIDIA gpus, similar
    to what was done for the CPU images. OpenMPI can now be built into the
    base image using the USE_MPI=1 option, such as:

    $> make USE_MPI="1" build-tf24-gpu

    After building this image and converting to Singularity, the image was
    tested on an IB cluster using the OSU benchmarks to verify
    performance.

    $ srun --mpi=pmi2 -p gpuNodes -n 2 --ntasks-per-node=1 singularity
    exec --bind /lus /lus/scratch/username/detAI-cuda-11.1-torch-1.9-tf-2.4-gpu-mpi.sif ./osu-micro-benchmarks-5.6.2/mpi/one-sided/osu_get_bw
    1                       2.06
    2                       4.21
    4                       8.41
    8                      16.83
    16                     33.77
    32                     66.42
    64                    128.51
    128                   246.12
    256                   493.93
    512                  1013.98
    1024                 1871.85
    2048                 3200.73
    4096                 4763.36
    8192                 6239.26
    16384                8293.17
    32768               11066.21
    65536               11517.27
    131072              11574.10
    262144              11581.30
    524288              11165.66
    1048576             10911.13
    2097152             10533.11
    4194304              9755.71

    Also tested with the TF2 MNIST test on 2 nodes using 8 gpus per node:

    $ srun --mpi=pmi2 -n 16 --ntasks-per-node=8 singularity exec --nv
    --bind /lus /lus/scratch/username/detAI-cuda-11.1-torch-1.9-tf-2.4-gpu-mpi.sif
    python /lus/scratch/username/tensorflow2_mnist.py >& log-gpu.txt

    In the log-gpu.txt file I verified that hvd.init() showed the correct
    MPI world size and ranks:

    $ grep "hvd\.size" log-gpu.txt
    hvd.local_rank(): 6, hvd.rank(): 6, hvd.size(): 16
    hvd.local_rank(): 2, hvd.rank(): 2, hvd.size(): 16
    hvd.local_rank(): 4, hvd.rank(): 12, hvd.size(): 16
    hvd.local_rank(): 6, hvd.rank(): 14, hvd.size(): 16
    hvd.local_rank(): 2, hvd.rank(): 10, hvd.size(): 16
    hvd.local_rank(): 4, hvd.rank(): 4, hvd.size(): 16
    hvd.local_rank(): 3, hvd.rank(): 11, hvd.size(): 16
    hvd.local_rank(): 0, hvd.rank(): 0, hvd.size(): 16
    hvd.local_rank(): 7, hvd.rank(): 7, hvd.size(): 16
    hvd.local_rank(): 0, hvd.rank(): 8, hvd.size(): 16
    hvd.local_rank(): 7, hvd.rank(): 15, hvd.size(): 16
    hvd.local_rank(): 3, hvd.rank(): 3, hvd.size(): 16
    hvd.local_rank(): 1, hvd.rank(): 9, hvd.size(): 16
    hvd.local_rank(): 5, hvd.rank(): 5, hvd.size(): 16
    hvd.local_rank(): 5, hvd.rank(): 13, hvd.size(): 16
    hvd.local_rank(): 1, hvd.rank(): 1, hvd.size(): 16

    The tensorflow2_mnist.py test completed as expected:

    $ tail log-gpu.txt
    Step #580          Loss: 0.049359
    Step #580          Loss: 0.064985
    Step #590          Loss: 0.040959
    Step #590          Loss: 0.183963
    Step #600          Loss: 0.039476
    Step #600          Loss: 0.103435
    Step #610          Loss: 0.049162
    Step #610          Loss: 0.048544
    Step #620          Loss: 0.084336
    Step #620          Loss: 0.046733

    Note: I was not able to build the tf1-gpu and tf2-gpu images because I
    encountered an error in the install.apex.sh similar to:

    ERROR: Command errored out with exit status 1: /opt/conda/bin/python
    -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] =
    '"'"'/tmp/pip-req-build-ao9mgp98/setup.py'"'"';
    __file__='"'"'/tmp/pip-req-build-ao9mgp98/setup.py'"'"';f =
    getattr(tokenize, '"'"'open'"'"', open)(__file__) if
    os.path.exists(__file__) else io.StringIO('"'"'from setuptools import
    setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"',
    '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))'
    --cpp_ext --cuda_ext install --record
    /tmp/pip-record-4l_4so8t/install-record.txt
    --single-version-externally-managed --compile --install-headers
    /opt/conda/include/python3.8/apex Check the logs for full command
    output.
    The command '/bin/sh -c /tmp/det_dockerfile_scripts/install_apex.sh'
    returned a non-zero code: 1
    Makefile:229: recipe for target 'build-tf2-gpu' failed

    This error also occurs when I try building on the current slurm-images
    branch without any of the changes from this PR.

* rebase fixes and build and publish mpi images

* skip arm64 for ompi

* bump to cuda 11.1.1 images

Co-authored-by: cdrickett <56980221+cdrickett@users.noreply.github.com>